#! /bin/bash

MES=" Перевіряю існування джерела"
MES_1_CORRECT=" Шлях ${1} правильний"
MES_2_FAIL=" Шкода але забули вказати другий параметр \\n Я не можу продовжити роботу"

# Запуск без параметрів
if [ "${1}" == "" ];then
    echo " Запуск скрипту"
    echo "          ${0} <source_path> <target_path>"
    exit
else # перший параметр коректний
    echo $MES
    if [ -e ${1} ]; then
        echo -e $MES_1_CORRECT
        # Забули один параметр
        if [[ "${2}" == "" ]];then
            echo -e $MES_2_FAIL
            exit
        else
            echo " Перевірки параметрів завершено"
            echo " Починаю роботу"
            if [ -e "${2}" ]; then
                echo " Я знайшов шлях ${2}"
                echo " Перевіряю"
                NewExt=$(date "+%d-%m-%y(%T)").bak
                if [ -L "${2}" ]; then
                    echo " Це символьне посилання"
                    echo " Читаю ${2} посилання => $(readlink ${2})"
                    if [ $(readlink "${2}") = "${1}" ];then
                        echo -e " \e[32mСимвольне посилання вказує на нас\e[0m"
                        echo " Робота виконана успішно"
                        exit
                    else
                        echo " Це посилання чуже"
                        echo " Архівую до ${2}.$NewExt"
                        mv "${2}" "${2}.$NewExt"
                        echo " Створюю"
                        ln -s "${1}" "${2}"
                        echo " Робота виконана успішно"
                    fi # заміна символьного посилання проведена
                else # це не символьне постлання
                    if [ -d "${2}" ]; then
                        echo " ${2} є каталогом"
                        echo " Архівую до ${2}.$NewExt"
                        mv "${2}" "${2}.$NewExt" #zip
                        echo " Створюю"
                        ln -s "${1}" "${2}"
                        echo " Робота виконана успішно"
                    else   
                        echo " ${2} є файлом"
                        echo " Архівую до ${2}.$NewExt"
                        mv "${2}" "${2}.$NewExt" #zip
                        echo " Створюю"
                        ln -s "${1}" "${2}"
                        echo " Робота виконана успішно"
                    fi
                fi
            else
                echo " Я шлях ${2} не існує" 
                echo " Створюю"
                ln -s "${1}" "${2}"
                echo " Робота виконана успішно" 
            fi
        fi        
    else # Шлях задано не правильно
        echo " Шкода але ${1} не існує. Перевірте правильність параметрів"
    fi  # Закінчив всі перевірки
    echo " Роботу завершено"
fi # кінець алгоритму

exit



NewExt=$(date "+%d-%m-%y(%T)").bak

# Перевіряємо існування того що заміщаємо
echo -e "Check existing \e[34m${2}\e[0m ..."
#     # Перевіряю існування шляху
    if [ -e "${2}" ]; then
        # якщо шлях існує
        echo -e "Path found"
        echo -e "Path \e[34m${2}\e[0m \e[32mexist\e[0m"
        # перевіряємо чи це не сімволічне посилання
        if [ -L "${2}" ]; then
            # це сімлінк
            echo -e "${2} is a symlink"
            # Перевіряю символьне посилання
            echo -e "Read symlink"
            echo -e "\e[34m${2}\e[0m => $(readlink ${2})"
            if [ $(readlink "${2}") = "${1}" ];then
                echo -e "\e[32mSymlink OK\e[0m"
            else
                # не наша тека
                mv "${2}" "${2}.$NewExt"
                ln -s "${1}" "${2}"
                echo -e "\e[32mSymlink OK\e[0m"
            fi
        else
            # це не посилання
            echo -e "Try open like folder"
            # перевіряємо чи не каталог
            if [ -d "${2}" ]; then
                # каталог
                echo -e "${2} is a folder"
                mv "${2}" "${2}.$NewExt"
                ln -s "${1}" "${2}"
                echo -e "\e[32mSymlink OK\e[0m"
            else
                # Виявляється це файл
                echo -e "\e[34m${2}\e[0m is a file"
                # Перейменовуємо
                mv "${2}" "${2}.$NewExt"
                # $(date "+%d-%m-%y(%T)").bak
                ln -s "${1}" "${2}"
                echo -e "\e[32mSymlink OK\e[0m"
            fi
        fi
    else
        # Шлях не зеайдено його треба створити
        echo -e "Path ${2} \e[31mno exists\e[0m"
        # Шлях стврлємо
        ln -s "${1}" "${2}"
        # Шлях створено
        echo -e "\e[32mCreate\e[0m"
        # Успішно
        echo -e "\e[32mSymlink OK\e[0m"
    fi