#! /bin/bash
# author: sam4uk
# version 0.2
# date: 1-12-24

# Рядки для локалізації
MES_BEGIN="\\t Запуск скрипту"
MES_NO_PARAM="\\t Скрипт запущено без параметрів\\n"
MES_CHECK_PATH="\\t \e[32mПеревіряю існування джерела\e[0m"
MES_1_CORRECT="\\t Шлях \e[34m${1}\e[0m правильний"
MES_2_FAIL="\\t Шкода але забули вказати \e[31mдругий параметр\e[0m \\n\\t Я \e[31mне можу продовжити роботу\e[0m"
MES_CHECK_FIN="\\t Перевірки параметрів завершено"
MES_START="\\t Починаю заміну"
MES_FOUND="\\t Я знайшов шлях \e[34m${2}\e[0m "
MES_CHECK="\\t \e[32mПеревіряю\e[0m"
MES_IS_FOLDER="\\t \e[34m${2}\e[0m є каталогом"
MES_IS_FILE="\\t \e[34m${2}\e[0m є файлом"
MES_IS_LINK="\\t \e[34m${2}\e[0m це символьне посилання"
MES_NO_EXIST="\\t шлях \e[34m${2}\e[0m не існує" 
MES_BAK_UP="\\t Архівую до"
MES_DO_MAKE="\\t Створюю посилання на \e[34m${1}\e[0m"
MES_JOB_OK="\\t Робота виконана успішно"
MES_READ_LINK="\\t Читаю \e[34m${2}\e[0m посилання =>"
MES_LINK_TO_ME="\\t \e[32mСимвольне посилання вказує на нас\e[0m"
MES_LINK_NOT_ME="\\t Це посилання \e[31mчуже\e[0m"
MES_JOK_FIN="\\t Роботу завершено"
MES_SORY="\\t Шкода але \e[32m${1}\e[0m \e[31mне існує\e[0m. Перевірте правильність параметрів"
# Рядки налаштування
ZIP_PARAM="-m9ry"

if [[ -z "${1}" ]];then # перевіряємо на наявність парамтрів, якщо без парамтерів то виводимо довідку
    echo -e $MES_NO_PARAM
    echo -e "\\t \\t deputy <source_path> <target_path>\\n"
    # echo -e "запуск без параметрів"
    # echo -e "запуск без параметрів"
    exit
elif [[ -n "${1}" ]];then # присутній перший параметр
    echo -e $MES_BEGIN
    echo -e $MES_CHECK_PATH
    if [ -e "${1}" ]; then # перевіряємо чи параметр є дісним шляхом
        echo -e $MES_1_CORRECT
        if [[ -z "${2}" ]]; then #перевіряємо другий парамтер
            echo -e $MES_2_FAIL
            exit # другий парамтр відсутній закінчуємо
        else # другий параметр присутній
            echo -e $MES_CHECK_FIN
            echo -e $MES_START
            if [ -e "${2}" ]; then # Це дійсний шлях
                echo -e $MES_FOUND
                echo -e $MES_CHECK
                NewExt=$(date "+%d-%m-%y(%T)").bak.zip
                if [ -h "${2}" ]; then # Може це постлання
                    echo -e $MES_IS_LINK
                    if [ $(readlink "${2}") = "${1}" ];then # посилання на нас самих?
                        echo -e $MES_READ_LINK "\e[34m$(readlink ${2})\e[0m"
                        echo -e $MES_LINK_TO_ME
                        echo -e $MES_JOB_OK
                        exit 
                    else # посилання на когось іншого
                        echo -e $MES_READ_LINK "\e[31m$(readlink ${2})\e[0m"
                        echo -e $MES_LINK_NOT_ME
                        echo -e "$MES_BAK_UP \e[34m${2}.$NewExt\e[0m"
                        mv "${2}" "${2}.$NewExt"
                        echo -e $MES_DO_MAKE
                        ln -s "${1}" "${2}"
                        echo -e $MES_JOB_OK
                    fi # тест посилання проведено
                elif [ -d "${2}" ]; then # Може це каталог
                        echo -e $MES_IS_FOLDER
                        echo -e "$MES_BAK_UP \e[34m${2}.$NewExt\e[0m\e[33m"
                        zip $ZIP_PARAM "${2}.$NewExt" "${2}"
                        echo -e  "\e[0m$MES_DO_MAKE"
                        ln -s "${1}" "${2}"
                        echo -e $MES_JOB_OK
                elif [ -f "${2}" ]; then # може звичайний файл
                        echo -e $MES_IS_FILE
                        echo -e "$MES_BAK_UP \e[34m${2}.$NewExt\e[0m\e[33m"
                        zip $ZIP_PARAM "${2}.$NewExt" "${2}"
                        echo -e "\e[0m$MES_DO_MAKE"
                        ln -s "${1}" "${2}"
                        echo -e $MES_JOB_OK
                fi # закінчена перевірка існуючого файлу
            else # шляху не існує
                echo -e $MES_NO_EXIST
                echo -e $MES_DO_MAKE
                ln -s "${1}" "${2}"
                echo -e $MES_JOB_OK
            fi #перевірку шляху завершено
        fi # перевірку другого парамтеру завершено
    else # Другий параметр не задано
        echo -e $MES_SORY
        exit # на вихід
    fi  # Закінчив всі перевірки
    echo -e $MES_JOK_FIN
    exit
fi # кінець алгоритму
exit